In [6]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])#生成2行3列的0矩阵
mat2 = tf.ones([3,2])#生成3行2列的全1矩阵
mat3 = tf.fill([2,3],15)#生成2行3列的填充矩阵，填充值是15
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))
    

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[15 15 15]
 [15 15 15]]


In [10]:
import tensorflow as tf
mat1 = tf.constant([[2],[3],[4]])
mat2 = tf.zeros_like(mat1)#维度与mat1相同的全0矩阵
mat3 = tf.linspace(0.0,2.0,11)#分割区间矩阵
mat4 = tf.random_uniform([2,3],-1,2)#区间为[-1,2],维度为2*3的随机矩阵
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
[[-0.32443738  0.22292924 -0.6861429 ]
 [ 1.3677576   1.467171    1.4671481 ]]
